// Unity C# reference source
// Copyright (c) Unity Technologies. For terms of use, see
// https://unity3d.com/legal/licenses/Unity_Reference_Only_License

namespace UnityEditor.ShaderFoundry
{
    internal enum NodeType : byte
    {
        // THIS ENUM MUST BE KEPT IN SYNC WITH THE ENUM IN NodeType.h
        Undefined = 0,
        List,
        ListElement,
        FileRoot,
        Identifier,
        Text,
        BooleanLiteral,
        CharacterLiteral,
        IntegerLiteral,
        FloatLiteral,
        StringLiteral,
        NamespacedIdentifier,
        TypeName,
        TemplateSpecifier,
        ArrayDimension,
        AttributeParameterListValue,
        AttributeParameter,
        Attribute,
        Variable,
        Interface,
        InterfaceField,
        Defines,
        Define,
        Include,
        Includes,
        PackageRequirement,
        PackageRequirements,
        Pragma,
        Pragmas,
        Tag,
        Tags,
        Struct,
        StructField,
        Function,
        FunctionParameter,
        Import,
        Imports,
        Block,
        Namespace,
        BlockSequence,
        BlockSequenceElement,
        LinkOverrideAccessor,
        LinkOverrideElementKeyword,
        LinkOverrideElementExpression,
        LinkOverrideElementConstantExpression,
        LinkOverride,
        LinkOverrides,
        CustomizationPoint,
        CustomizationPointImplementation,
        CustomAttribute,
        ConstructorSignature,
        ConstructorSignatureParameter,
        Lod,
        CopyRule,
        PassStageSetting,
        PassStageSetup,
        PassStage,
        Pass,
        Fallback,
        Dependency,
        CustomEditor,
        Extensions,
        Template,
        BlockShaderInterface,
        RegisterTemplateStatement,
        RegisterTemplatesWithInterface,
        GeneratorSetting,
        BlockShaderSetting,
        BlockShaderSettings,
        BlockShader,
        RenderStateProperty,
        RenderStateTargetSpecifier,
        RenderStateNamedValue,
        RenderState,
        RenderStates,
        Keyword,
        Keywords,
        Resource,
        PropertyOrderItem,
        PropertyOrderGroup,
        PropertyOrder,
        BlockInterface,
        OutputLinker,

        Count,
        // THIS ENUM MUST BE KEPT IN SYNC WITH THE ENUM IN NodeType.h
    };
}
