// Unity C# reference source
// Copyright (c) Unity Technologies. For terms of use, see
// https://unity3d.com/legal/licenses/Unity_Reference_Only_License

// NOTE: the build system includes this source file in ALL Editor modules

using System.Runtime.CompilerServices;
using UnityEngine;

[assembly: AssemblyIsEditorAssembly]

// TODO: over time, remove the InternalsVisibleTo attributes from this section
// You can start by moving them to EditorCoreModuleAssemblyInfo.cs to reduce internal visibility
// To remove a line in there, the target assembly must not depend on _any_ internal API from built-in Editor modules


// ADD_NEW_PLATFORM_HERE
[assembly: InternalsVisibleTo("Unity.LiveNotes")]
[assembly: InternalsVisibleTo("Unity.Audio.Tests")]
[assembly: InternalsVisibleTo("Unity.Burst")]
[assembly: InternalsVisibleTo("Unity.Burst.Editor")]
[assembly: InternalsVisibleTo("UnityEditor.BurstModule")]
[assembly: InternalsVisibleTo("Unity.CollabProxy.Editor")]
[assembly: InternalsVisibleTo("Unity.PlasticSCM.Editor")]
[assembly: InternalsVisibleTo("Unity.PlasticSCM.EditorTests")]
[assembly: InternalsVisibleTo("UnityEditor.Advertisements")]
[assembly: InternalsVisibleTo("Unity.PackageManager")]
[assembly: InternalsVisibleTo("Unity.PackageManagerStandalone")]
[assembly: InternalsVisibleTo("Unity.AndroidBuildPipeline")]
[assembly: InternalsVisibleTo("Unity.Automation")]
[assembly: InternalsVisibleTo("UnityEngine.Common")]
[assembly: InternalsVisibleTo("Unity.PureCSharpTests")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Android")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Android.CommonUtils")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Animation")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.AssetImporting")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.BuildPipeline")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Builds")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Insights")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.CrashReporting")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.DeploymentTargets")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.EditorApplication")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.EditorDeeplink")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.EditorUI")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.GameCore")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.GameView")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.IncrementalBuilds")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Lightmapping")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Metro")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Misc")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.PackageManager")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Profiler")]
[assembly: InternalsVisibleTo("Unity.Modules.ProfilerEditor.MemorySnapshot.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.ProfilerEditor.MemorySnapshot.Tests.Playmode")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.PS4")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.PS5")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Switch")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Switch2")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.NintendoCore")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Rendering")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.SceneVisibility")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.ScriptCompilation")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.ShortcutManager")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.UIToolkit")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Framework.PackageManager")]
[assembly: InternalsVisibleTo("Unity.DeploymentTests.Services")]
[assembly: InternalsVisibleTo("Unity.PerformanceIntegrationTests")]
[assembly: InternalsVisibleTo("Unity.Timeline.Editor")]
[assembly: InternalsVisibleTo("Unity.PackageManagerUI.Develop.Editor")]
[assembly: InternalsVisibleTo("Unity.DeviceSimulator.Editor")]
[assembly: InternalsVisibleTo("Unity.Timeline.EditorTests")]
[assembly: InternalsVisibleTo("Unity.Modules.AdaptivePerformanceEditor.Tests.Editor")]
[assembly: InternalsVisibleTo("UnityEditor.Graphs")]
[assembly: InternalsVisibleTo("UnityEditor.UWP.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.iOS.Extensions.Common")]
[assembly: InternalsVisibleTo("UnityEditor.Apple.Extensions.Common")]
[assembly: InternalsVisibleTo("UnityEditor.iOS.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.VisionOS.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.AppleTV.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Android.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.XboxOne.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.PS4.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.PS5.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Switch.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Switch2.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.WebGL.Extensions")]
[assembly: InternalsVisibleTo("Unity.Automation.Players.WebGL")]
[assembly: InternalsVisibleTo("Unity.WebGL.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.LinuxStandalone.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.CloudRendering.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.EmbeddedLinux.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.QNX.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Kepler.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.WindowsStandalone.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.OSXStandalone.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Lumin.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.GameCoreScarlett.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.GameCoreXboxOne.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.GameCoreCommon.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Networking")]
[assembly: InternalsVisibleTo("UnityEngine.Networking")]
[assembly: InternalsVisibleTo("Unity.Analytics.Editor")]
[assembly: InternalsVisibleTo("UnityEditor.Analytics")]
[assembly: InternalsVisibleTo("UnityEditor.Purchasing")]
[assembly: InternalsVisibleTo("UnityEditor.Lumin")]
[assembly: InternalsVisibleTo("UnityEditor.EditorTestsRunner")]
[assembly: InternalsVisibleTo("UnityEditor.TestRunner")]
[assembly: InternalsVisibleTo("UnityEditor.TestRunner.Tests")]
[assembly: InternalsVisibleTo("Unity.Compiler.Client")]
[assembly: InternalsVisibleTo("ExternalCSharpCompiler")]
[assembly: InternalsVisibleTo("UnityEngine.TestRunner")]
[assembly: InternalsVisibleTo("Unity.Modules.AssetDatabase.ImportActivityWindow.Tests")]
[assembly: InternalsVisibleTo("Unity.Modules.AssetDatabase.UnityPackage.Tests.Editor")]
[assembly: InternalsVisibleTo("UnityEditor.VR")]
[assembly: InternalsVisibleTo("Unity.RuntimeTests")]
[assembly: InternalsVisibleTo("Unity.RuntimeTests.Framework")]
[assembly: InternalsVisibleTo("Assembly-CSharp-Editor-firstpass-testable")]
[assembly: InternalsVisibleTo("Assembly-CSharp-Editor-testable")]
[assembly: InternalsVisibleTo("Unity.CrossModule.PlayMode.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Module.AssetDatabase.DanglingComponents.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.ComponentUtility.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.AssetType.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.DragAndDrop.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.SceneHierarchy.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.SceneHierarchy.Tests.Common")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.NestedPrefabsBackwardsCompatibility.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.NestedPrefabsFrontEnd.Tests.Editor")]
[assembly: InternalsVisibleTo("UnityEditor.ContentLoadModule")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: InternalsVisibleTo("UnityEditor.InteractiveTutorialsFramework")]
[assembly: InternalsVisibleTo("UnityEditor.Networking")]
[assembly: InternalsVisibleTo("UnityEditor.UI")]
[assembly: InternalsVisibleTo("UnityEditor.AR")]
[assembly: InternalsVisibleTo("UnityEditor.SpatialTracking")]
[assembly: InternalsVisibleTo("Unity.WindowsMRAutomation")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.001")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.002")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.003")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.004")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.005")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.006")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.007")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.008")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.009")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.010")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.011")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.012")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.013")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.014")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.015")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.016")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.017")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.018")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.019")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.020")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.021")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.022")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.023")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.024")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridge.ShaderGraph.Editor")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridgeDev.001")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridgeDev.002")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridgeDev.003")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridgeDev.004")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEditorBridgeDev.005")]
[assembly: InternalsVisibleTo("Unity.XR.Remoting.Editor")]
[assembly: InternalsVisibleTo("UnityEngine.Common")]
[assembly: InternalsVisibleTo("Unity.UI.Builder.Editor")]
[assembly: InternalsVisibleTo("Unity.UI.TestFramework.Editor.Tests")] // for UI Test Framework
[assembly: InternalsVisibleTo("UnityEditor.UIBuilderModule")]
[assembly: InternalsVisibleTo("UnityEditor.VectorGraphicsModule")]
[assembly: InternalsVisibleTo("Unity.UI.Builder.EditorTests")]
[assembly: InternalsVisibleTo("Unity.Modules.UIToolkitAuthoring.Tests.Editor")]
[assembly: InternalsVisibleTo("UnityEditor.UIToolkitAuthoringModule")]
[assembly: InternalsVisibleTo("Unity.GraphViewTestUtilities.Editor")]
[assembly: InternalsVisibleTo("Unity.ProBuilder.Editor")]
[assembly: InternalsVisibleTo("Unity.2D.Sprite.Editor")]
[assembly: InternalsVisibleTo("Unity.2D.Sprite.EditorTests")]
[assembly: InternalsVisibleTo("Unity.2D.Tilemap.Editor")]
[assembly: InternalsVisibleTo("Unity.2D.Tilemap.Editor.Experimental")]
[assembly: InternalsVisibleTo("Unity.2D.Tilemap.EditorTests")]
[assembly: InternalsVisibleTo("Unity.PackageCleanConsoleTest.Editor")]
[assembly: InternalsVisibleTo("Unity.TextCore.Editor.Tests")]
[assembly: InternalsVisibleTo("UnityEditor.TextCoreTextEngineModule")]
[assembly: InternalsVisibleTo("Unity.TextMeshPro.Editor")]
[assembly: InternalsVisibleTo("Unity.Animation.Editor.AnimationWindow")]
[assembly: InternalsVisibleTo("Unity.VisualEffectGraph.Editor")]
[assembly: InternalsVisibleTo("Unity.Testing.VisualEffectGraph.EditorTests")]
[assembly: InternalsVisibleTo("Unity.VisualEffectGraph.EditorTests")]
[assembly: InternalsVisibleTo("Unity.RenderPipelines.Multiple_SRP.EditorTests")]
[assembly: InternalsVisibleTo("Unity.ShaderGraph.Editor")]
[assembly: InternalsVisibleTo("Unity.Testing.SRP.Universal.Foundation.Editor")]

[assembly: InternalsVisibleTo("Unity.SceneTemplate.Editor")]
[assembly: InternalsVisibleTo("com.unity.purchasing.udp.Editor")]
[assembly: InternalsVisibleTo("com.unity.search.extensions.editor")]
[assembly: InternalsVisibleTo("UnityEditor.Android.Extensions")]

[assembly: InternalsVisibleTo("Unity.Entities.Build")]

[assembly: InternalsVisibleTo("Unity.Muse.Chat.Bridge")]
[assembly: InternalsVisibleTo("Unity.AI.Assistant.Bridge.Editor")]

[assembly: InternalsVisibleTo("Unity.Multiplayer.Playmode.Editor.Bridge")]
[assembly: InternalsVisibleTo("Unity.DedicatedServer.Editor.Bridge")]

[assembly: InternalsVisibleTo("Unity.Video.Tests")]
[assembly: InternalsVisibleTo("Unity.Video.PlayModeTests")]
[assembly: InternalsVisibleTo("Unity.Video.EditModeTests")]

[assembly:InternalsVisibleTo("Unity.AI.Navigation.Editor")]

[assembly: InternalsVisibleTo("Unity.Scenes")]


[assembly: InternalsVisibleTo("UnityEditor.Switch.Tests")]
[assembly: InternalsVisibleTo("UnityEditor.Switch2.Tests")]

[assembly: InternalsVisibleTo("UnityEditor.BuildProfileModule.Tests")]
//For add Component tests
[assembly: InternalsVisibleTo("Unity.Modules.AdaptivePerformanceEditor.Tests.Playmode.EditorScripts.AssetCreation")]


[assembly: InternalsVisibleTo("UnityEditor.PS4.Tests")]

[assembly: InternalsVisibleTo("UnityEditor.PS5.Tests")]

[assembly: InternalsVisibleTo("Unity.Automation.Players.EmbeddedLinux")]
[assembly: InternalsVisibleTo("Unity.Automation.Players.QNX")]

[assembly: InternalsVisibleTo("UnityEditor.GraphToolkitModule")]

// Module test assemblies
[assembly: InternalsVisibleTo("Unity.Modules.Scripting.APIUpdater.Misc.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Scripting.APIUpdater.UpdateSameProjectAsConfigs.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Scripting.APIUpdater.PackManIntegration.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CodeEditors.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.iOSExtensions.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Licensing.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.PlatformIcons.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.BuildProfileEditor.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.UI.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Multiplayer.Server.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.AssetDatabase.AssetPostProcessor.Tests.Editor")]
// This should move with the AnimationWindow to a module at some point
[assembly: InternalsVisibleTo("Unity.Modules.Animation.AnimationWindow.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Physics.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.GI.EditorBake.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.GI.LightProbes.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Physics2D.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.U2D.NineSlice.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.GI.Prefabs.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.PackageManagerUI.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.ShaderCompilationEditor.ShaderCompilation.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.ShaderCompilationEditor.ShaderUtil.Tests.Editor")]

[assembly: InternalsVisibleTo("Unity.Tests.Shared")]

// Test Assemblies
[assembly: InternalsVisibleTo("Unity.Core.UnityEvent.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Core.Scripting.AssemblyVersion.Tests.Editor")]

// Performance Tests Assemblies
[assembly: InternalsVisibleTo("Unity.PerformanceTesting.IMGUI")]

// Tests\CrossModulePackages\ScriptableRenderPipeline
[assembly: InternalsVisibleTo("Unity.CrossModule.ScriptableRenderPipeline.Tests.Runtime")]
[assembly: InternalsVisibleTo("Unity.CrossModule.ScriptableRenderPipeline.Tests.Editor")]

[assembly: InternalsVisibleTo("Unity.Core.EditorWindowManagement.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.InspectorFramework.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.EditorUtils.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Umpe.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.Undo.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.UnityType.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.Camera.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Core.VersionControl.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.ProjectAuditor.EditorTests")]
[assembly: InternalsVisibleTo("Unity.Modules.GI.Analytics.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.CrossModule.AssetLoading.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.SceneTemplateEditor.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.InspectorWindow.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Terrain.Tests.Editor")]

