// Unity C# reference source
// Copyright (c) Unity Technologies. For terms of use, see
// https://unity3d.com/legal/licenses/Unity_Reference_Only_License

using System;

namespace Unity.Hierarchy
{
    /// <summary>
    /// Cell Descriptor used to register a new Cell for a specific Node Type in the Hierarchy.
    /// Allows user to create custom UI to edit or display data of this Node in the Cell corresponding to a specific Column.
    /// </summary>
    public sealed class HierarchyViewCellDescriptor
    {
        bool m_IsColumnBound;

        /// <summary>
        /// ColumnId used to register the Cell to.
        /// </summary>
        public string ColumnId { get; }

        /// <summary>
        /// NodeHandler type used to manage the Node of this Cell.
        /// </summary>
        public Type HandlerType { get; }

        /// <summary>
        /// Callback triggered when the cell is bound.
        /// </summary>
        public Action<HierarchyViewCell> BindCell;

        /// <summary>
        /// Callback triggered when the cell is unbound. The VisualElement content of the Cell will automatically be cleared out. User should only Dispose of custom resources or
        /// unregister from events.
        /// </summary>
        public Action<HierarchyViewCell> UnbindCell;

        /// <summary>
        /// Callback triggered when the column containing Cell generated by this descriptor is bound to the view.
        /// </summary>
        public Action<HierarchyViewColumnDescriptor, HierarchyView> BindColumn;

        /// <summary>
        /// Callback triggered when the column containing Cell generated by this descriptor is unbound from the view.
        /// </summary>
        public Action<HierarchyViewColumnDescriptor, HierarchyView> UnbindColumn;

        /// <summary>
        /// If true, the children of the HierarchyViewCell will be deleted when the cell is unbound.
        /// </summary>
        public bool ClearCellContent { get; set; }

        /// <summary>
        /// User data
        /// </summary>
        public object UserData { get; set; }

        /// <summary>
        /// Create a new Cell Descriptor.
        /// </summary>
        /// <param name="columnId">Column ID of the column used to host cell for this descriptor. </param>
        /// <param name="handlerType">Type of the NodeHandler that will be used to modify data of this cell.</param>
        public HierarchyViewCellDescriptor(string columnId, Type handlerType = null)
        {
            ColumnId = columnId;
            HandlerType = handlerType;
            ClearCellContent = true;
        }

        internal void InvokeBindColumn(HierarchyViewColumnDescriptor descriptor, HierarchyView view)
        {
            if (m_IsColumnBound)
                return;
            BindColumn?.Invoke(descriptor, view);
            m_IsColumnBound = true;
        }

        internal void InvokeUnbindColumn(HierarchyViewColumnDescriptor descriptor, HierarchyView view)
        {
            if (!m_IsColumnBound)
                return;
            UnbindColumn?.Invoke(descriptor, view);
            m_IsColumnBound = false;
        }

        /// <summary>
        /// Validate that a Column Descriptor is valid for this Cell Descriptor.
        /// </summary>
        /// <param name="colDesc">Column Descriptor</param>
        /// <returns>Returns true of this CellDescirptor has the same ColumnId as the ColumnDescriptor parameter.</returns>
        public bool ValidForColumn(HierarchyViewColumnDescriptor colDesc)
        {
            return ColumnId == colDesc.Id;
        }

        public override string ToString()
        {
            var handlerType = HandlerType != null ? HandlerType.Name : "<GenericNodeHandler>";
            return $"{ColumnId} - {handlerType}";
        }
    }
}
