// Unity C# reference source
// Copyright (c) Unity Technologies. For terms of use, see
// https://unity3d.com/legal/licenses/Unity_Reference_Only_License

using System;

namespace Unity.Hierarchy
{
    /// <summary>
    /// Provides a cell descriptor used to register a new <see cref="HierarchyViewCell"/> for a specific <see cref="HierarchyNodeTypeHandler"/> type in the <see cref="Hierarchy"/>.
    /// Use this class to create custom UI to edit or display data for a node in a <see cref="HierarchyViewCell"/> that corresponds to a <see cref="HierarchyViewColumn"/>.
    /// </summary>
    /// <example>
    /// The following example creates a column in the Hierarchy window that displays the icons of each component attached to a GameObject. It uses `HierarchyViewCellDescriptor` to register a custom cell binding for the `HierarchyGameObjectHandler` type that displays the component icons in the custom Hierarchy column. 
    ///
    /// The example requires the USS file `ComponentsColumn.uss`.
    /// To use this example, save the script and USS file in a folder called `Assets/Editor/ComponentsColumn`. Scripts in an `Editor` folder can use the Hierarchy module API without additional setup. If you save the script outside of an `Editor` folder, you must enable the Hierarchy built-in module in the **Package Manager** window, which also adds the module to your Player builds. 
    ///
    /// After adding the script to your project, enable the new **Components** column in the Hierarchy window for it to display.
    /// <code source="../../../Tests/EditModeAndPlayModeTests/HierarchySamples/Assets/Editor/ComponentsColumn/ComponentsColumn.cs"/>
    /// </example>
    /// <example>
    /// The following example shows how to style `ComponentsColumn.uss`.
    /// <code source="../../../Tests/EditModeAndPlayModeTests/HierarchySamples/Assets/Editor/ComponentsColumn/ComponentsColumn.uss"/>
    /// </example>
    public sealed class HierarchyViewCellDescriptor
    {
        bool m_IsColumnBound;

        /// <summary>
        /// Gets the column identifier that this cell is registered to.
        /// </summary>
        public string ColumnId { get; }

        /// <summary>
        /// Gets the <see cref="HierarchyNodeTypeHandler"/> type used to manage the node of this cell.
        /// </summary>
        public Type HandlerType { get; }

        /// <summary>
        /// Callback triggered when the <see cref="HierarchyViewCell"/> is bound.
        /// </summary>
        public Action<HierarchyViewCell> BindCell;

        /// <summary>
        /// Callback triggered when the <see cref="HierarchyViewCell"/> is unbound. The <see cref="UnityEngine.UIElements.VisualElement"/> content of the cell is automatically cleared. Use this callback to dispose of custom resources or
        /// unregister from events.
        /// </summary>
        public Action<HierarchyViewCell> UnbindCell;

        /// <summary>
        /// Callback triggered when the column containing a <see cref="HierarchyViewCell"/> generated by this descriptor is bound to the <see cref="HierarchyView"/>.
        /// </summary>
        public Action<HierarchyViewColumnDescriptor, HierarchyView> BindColumn;

        /// <summary>
        /// Callback triggered when the column containing a <see cref="HierarchyViewCell"/> generated by this descriptor is unbound from the <see cref="HierarchyView"/>.
        /// </summary>
        public Action<HierarchyViewColumnDescriptor, HierarchyView> UnbindColumn;

        /// <summary>
        /// If true, the children of the <see cref="HierarchyViewCell"/> are deleted when the cell is unbound.
        /// </summary>
        public bool ClearCellContent { get; set; }

        /// <summary>
        /// Gets or sets custom user data associated with this descriptor.
        /// </summary>
        public object UserData { get; set; }

        /// <summary>
        /// Creates a new <see cref="HierarchyViewCellDescriptor"/>.
        /// </summary>
        /// <param name="columnId">The column identifier of the column that hosts cells for this descriptor.</param>
        /// <param name="handlerType">The type of the <see cref="HierarchyNodeTypeHandler"/> used to modify data of this cell.</param>
        public HierarchyViewCellDescriptor(string columnId, Type handlerType = null)
        {
            ColumnId = columnId;
            HandlerType = handlerType;
            ClearCellContent = true;
        }

        internal void InvokeBindColumn(HierarchyViewColumnDescriptor descriptor, HierarchyView view)
        {
            if (m_IsColumnBound)
                return;
            BindColumn?.Invoke(descriptor, view);
            m_IsColumnBound = true;
        }

        internal void InvokeUnbindColumn(HierarchyViewColumnDescriptor descriptor, HierarchyView view)
        {
            if (!m_IsColumnBound)
                return;
            UnbindColumn?.Invoke(descriptor, view);
            m_IsColumnBound = false;
        }

        /// <summary>
        /// Validates that a <see cref="HierarchyViewColumnDescriptor"/> is valid for this cell descriptor.
        /// </summary>
        /// <param name="colDesc">The <see cref="HierarchyViewColumnDescriptor"/> to validate.</param>
        /// <returns>Returns true if this cell descriptor has the same column identifier as the ColDesc parameter. Otherwise, returns false.</returns>
        public bool ValidForColumn(HierarchyViewColumnDescriptor colDesc)
        {
            return ColumnId == colDesc.Id;
        }

        public override string ToString()
        {
            var handlerType = HandlerType != null ? HandlerType.Name : "<GenericNodeHandler>";
            return $"{ColumnId} - {handlerType}";
        }
    }
}
