// Unity C# reference source
// Copyright (c) Unity Technologies. For terms of use, see
// https://unity3d.com/legal/licenses/Unity_Reference_Only_License

namespace UnityEditor.ShaderFoundry
{
    internal enum DataType : ushort
    {
        // THIS ENUM MUST BE KEPT IN SYNC WITH THE ENUM IN DataType.h
        Unknown = 0,

        StartStaticSized,
        // Static sized types
        ShaderAttributeParameter = StartStaticSized,
        ShaderAttribute,
        RenderStateDescriptor,
        RenderStateNamedValue,
        RenderStateProperty,
        RenderStateTargetSpecifier,
        DefineDescriptor,
        IncludeDescriptor,
        KeywordDescriptor,
        PragmaDescriptor,
        TagDescriptor,
        FunctionParameter,
        ShaderFunction,
        StructField,
        ShaderType,
        Block,
        CustomizationPoint,
        TemplatePass,
        Template,
        ShaderDependency,
        ShaderCustomEditor,
        PackageRequirement,
        CopyRule,
        LinkOverride,
        LinkAccessor,
        LinkElement,
        BlockSequenceElement,
        CustomizationPointImplementation,
        StageDescription,
        BlockShaderInterface,
        BlockShader,
        InterfaceRegistrationStatement,
        RegisterTemplatesWithInterface,
        Namespace,
        Boolean,
        Float,
        Integer,
        EnumLiteral,
        Array,
        String,
        EmptyString,
        Location,
        CustomAttributeDefinition,
        CustomAttributeInstance,
        ConstructorSignature,
        ConstructorSignatureParameter,
        AttributeDefault,
        AttributeProperty,
        AttributeRange,
        AttributeSampler,
        AttributeTexture,
        AttributeBoolKeyword,
        AttributeEnumKeyword,
        AttributeSystem,
        AttributeSemantic,
        AttributeConstraint,
        AttributeRuntimeBuffer,
        AttributeConstantBuffer,
        AttributeCopyToMaterialProperty,
        BlockSequence,
        AttributeShaderOverrideName,
        AttributeAllowImplicitLinking,
        AttributeColor,
        // THIS ENUM MUST BE KEPT IN SYNC WITH THE ENUM IN DataType.h -- ALSO ADD THE TYPE MAPPING TO Initialize()
        // ALSO ADD THE TYPE MAPPING TO DataTypeStatic.Initialize()
    };
}
