// Unity C# reference source
// Copyright (c) Unity Technologies. For terms of use, see
// https://unity3d.com/legal/licenses/Unity_Reference_Only_License

// NOTE: the build system includes this source file in ALL modules (Runtime and Editor)

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: UnityEngine.UnityEngineModuleAssembly]

// required for the type forwarders
[assembly: InternalsVisibleTo("UnityEngine")]
[assembly: InternalsVisibleTo("UnityEditor")]

// TODO: over time, remove the InternalsVisibleTo attributes from this section
// To remove a line in there, the target assembly must not depend on _any_ internal API from built-in modules

[assembly: InternalsVisibleTo("UnityEngine.Advertisements")]
[assembly: InternalsVisibleTo("UnityEditor.Advertisements")]
[assembly: InternalsVisibleTo("Unity.Analytics.Editor")]
[assembly: InternalsVisibleTo("UnityEditor.Analytics")]
[assembly: InternalsVisibleTo("UnityEngine.UnityAnalyticsCommon")]
[assembly: InternalsVisibleTo("UnityEditor.Purchasing")]
[assembly: InternalsVisibleTo("Unity.PureCSharpTests")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")] // for Moq
[assembly: InternalsVisibleTo("UnityEditor.Graphs")]
[assembly: InternalsVisibleTo("UnityEditor.XboxOne.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.PS4.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.PS5.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Switch.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Switch2.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.UWP.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.GameCoreScarlett.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.GameCoreXboxOne.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.GameCoreCommon.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.WindowsStandalone.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.WebGL.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.EmbeddedLinux.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.LinuxStandalone.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.QNX.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Kepler.Extensions")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.ObjectManagement.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.TagManager.Tests.Editor")]
[assembly: InternalsVisibleTo("Assembly-CSharp-Editor-testable")]
[assembly: InternalsVisibleTo("Assembly-CSharp-Editor-firstpass-testable")]
[assembly: InternalsVisibleTo("ObjectSelector")] /*UCBP-REMOVE*/
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.ObjectNames.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.TreeViewExamples.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.ObjectFactory.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.AssetType.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.AssetDatabase.AssetPostProcessor.Tests.Editor")]
[assembly: InternalsVisibleTo("UnityEditor.iOS.Extensions.Common")]
[assembly: InternalsVisibleTo("UnityEditor.Apple.Extensions.Common")]
[assembly: InternalsVisibleTo("UnityEditor.VisionOS.Extensions")]
[assembly: InternalsVisibleTo("UnityEditor.Android.Extensions")]
[assembly: InternalsVisibleTo("Unity.AndroidBuildPipeline")]
[assembly: InternalsVisibleTo("UnityEditor.OSXStandalone.Extensions")]
[assembly: InternalsVisibleTo("Unity.Timeline.Editor")] // for Driven Properties
[assembly: InternalsVisibleTo("Unity.Timeline.EditorTests")]
[assembly: InternalsVisibleTo("UnityEditor.InteractiveTutorialsFramework")]
[assembly: InternalsVisibleTo("Unity.2D.Tilemap.Editor")]
[assembly: InternalsVisibleTo("Unity.2D.Tilemap.EditorTests")]
[assembly: InternalsVisibleTo("Unity.DeviceSimulator.Editor")]
[assembly: InternalsVisibleTo("Unity.UIElements")]
[assembly: InternalsVisibleTo("Unity.UIElements.Editor")]
[assembly: InternalsVisibleTo("UnityEditor.UIElementsModule")]
[assembly: InternalsVisibleTo("UnityEditor.UIElementsGameObjectsModule")]
[assembly: InternalsVisibleTo("Unity.UI.TestFramework.Editor")] // for UI Test Framework
[assembly: InternalsVisibleTo("Unity.Modules.UIToolkitAuthoring.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Tiny.Rendering.Authoring")]
[assembly: InternalsVisibleTo("Unity.Tiny.Authoring")]
[assembly: InternalsVisibleTo("Unity.ImageConversionTests")]
[assembly: InternalsVisibleTo("Unity.PathTracing.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.ParticleSystem.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.NestedPrefabsBackwardsCompatibility.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.NestedPrefabsFrontEnd.Tests.Editor")]

// This should move with the AnimationWindow to a module at some point
[assembly: InternalsVisibleTo("Unity.Modules.Animation.AnimationWindow.Tests.Editor")]

[assembly: InternalsVisibleTo("Unity.Motion.Editor.AnimationWindow")]

[assembly: InternalsVisibleTo("Unity.Modules.SpriteAPI.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.SpriteDeform.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.SpriteShape.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.DrivenProperties.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.SceneHierarchy.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.SceneHierarchy.Tests.Common")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.DragAndDrop.Tests.Editor")]

[assembly: InternalsVisibleTo("UnityEditor.ContentLoadModule")]

[assembly: InternalsVisibleTo("Unity.Modules.Core.Tests.ColorPicker")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.Tests.TreeViewControl")]

[assembly: InternalsVisibleTo("Unity.Hierarchy.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.Hierarchy.Editor.PerformanceTests")]

[assembly: InternalsVisibleTo("Unity.Modules.UI.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.XR.InputProvider.Tests.Playmode")]

[assembly: InternalsVisibleTo("Unity.Modules.Core.TextureMipLimit.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.TextureStreaming.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.TextureGenerator.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Streaming.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.PackageManagerUI.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.ProfilerEditor.MemorySnapshot.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.ShaderCompilationEditor.ShaderUtil.Tests.Editor")]


[assembly: InternalsVisibleTo("UnityEngine.Networking")]
[assembly: InternalsVisibleTo("UnityEngine.Cloud")]
[assembly: InternalsVisibleTo("UnityEngine.Cloud.Service")]
[assembly: InternalsVisibleTo("Unity.Analytics")]
[assembly: InternalsVisibleTo("UnityEngine.Analytics")]
[assembly: InternalsVisibleTo("UnityEngine.UnityAnalyticsCommon")]
[assembly: InternalsVisibleTo("UnityEngine.Advertisements")]
[assembly: InternalsVisibleTo("UnityEngine.Purchasing")]
[assembly: InternalsVisibleTo("UnityEngine.TestRunner")]
[assembly: InternalsVisibleTo("Unity.Automation")]
[assembly: InternalsVisibleTo("Unity.Burst")]
[assembly: InternalsVisibleTo("Unity.Burst.Editor")]
[assembly: InternalsVisibleTo("Unity.DeploymentTests.Services")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.2D")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Android")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Android.Deployment")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Android.Tooling")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Android.CommonUtils")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Android.Application")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Android.Lifecycle")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Android.Uaal")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Android.PlayerBuildAndRun")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Animation")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.AssetBundles")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.AssetImporting")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Builds")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.CommandLine")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.EditorUI")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.IncrementalBuilds")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Lightmapping")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Mecanim")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Misc")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Profiler")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.SceneLoading")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.ScriptCompilation")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Scripting")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Stripping")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Serialization")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.StandaloneBuilds")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.UIToolkit")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.ExternalVersionControl")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.UnityAnalytics")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Timeline")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Framework")]
[assembly: InternalsVisibleTo("Unity.IntegrationTests.Framework.Tests")]
[assembly: InternalsVisibleTo("Unity.PathTracing.Runtime")]
[assembly: InternalsVisibleTo("Unity.RuntimeTests")]
[assembly: InternalsVisibleTo("Unity.RuntimeTests.Framework")]
[assembly: InternalsVisibleTo("Unity.RuntimeTests.Framework.Tests")]
[assembly: InternalsVisibleTo("Unity.PerformanceTests.RuntimeTestRunner.Tests")]
[assembly: InternalsVisibleTo("Unity.RuntimeTests.AllIn1Runner")]
[assembly: InternalsVisibleTo("Unity.Timeline")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.CoreTests.Tests.Runtime")]
[assembly: InternalsVisibleTo("Assembly-CSharp-testable")]
[assembly: InternalsVisibleTo("Unity.CrossModule.PlayMode.Tests.Runtime")]
[assembly: InternalsVisibleTo("Assembly-CSharp-firstpass-testable")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.GameObject.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.GameObject.Tests.Runtime")]
[assembly: InternalsVisibleTo("Unity.Modules.CoreEditor.EditorObjectChangeEvents.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.SynchronizationContext.Tests.Editor")]
[assembly: InternalsVisibleTo("UnityEngine.SpatialTracking")]
[assembly: InternalsVisibleTo("GoogleAR.UnityNative")]
[assembly: InternalsVisibleTo("Unity.WindowsMRAutomation")]
[assembly: InternalsVisibleTo("UnityEngine.SpriteShapeModule")]
[assembly: InternalsVisibleTo("Unity.RenderPipelines.Universal.2D.Runtime")]
[assembly: InternalsVisibleTo("Unity.RenderPipelines.Universal.2D.Editor.Overrides")]
[assembly: InternalsVisibleTo("UnityEngine.TestTools.Graphics.Contexts")]
[assembly: InternalsVisibleTo("Unity.2D.Common.Editor")]
[assembly: InternalsVisibleTo("Unity.2D.Sprite.Editor")]
[assembly: InternalsVisibleTo("Unity.2D.Sprite.EditorTests")]
[assembly: InternalsVisibleTo("Universal2DGraphicsTests")]
[assembly: InternalsVisibleTo("Unity.UI.Builder.Editor")]
[assembly: InternalsVisibleTo("UnityEditor.UIBuilderModule")]
[assembly: InternalsVisibleTo("Unity.UI.Builder.EditorTests")]
[assembly: InternalsVisibleTo("Unity.UIElements")]
[assembly: InternalsVisibleTo("UnityEngine.UIElementsGameObjectsModule")]
[assembly: InternalsVisibleTo("Unity.UIElements.Editor")]
[assembly: InternalsVisibleTo("Unity.UIElements.PlayModeTests")]
[assembly: InternalsVisibleTo("Unity.UI.TestFramework.Runtime")]
[assembly: InternalsVisibleTo("Unity.Modules.ParticleSystem.Tests")]
[assembly: InternalsVisibleTo("Unity.Modules.ParticleSystem.Rendering.Tests")]
[assembly: InternalsVisibleTo("UnityEditor.UIElements.Tests")]
[assembly: InternalsVisibleTo("UnityEngine.UIElements.Tests.Base")]
[assembly: InternalsVisibleTo("UnityEngine.UIElements.Tests.Bindings")]
[assembly: InternalsVisibleTo("UnityEngine.UIElements.Tests.Controls")]
[assembly: InternalsVisibleTo("UnityEngine.UIElements.Tests.StyleSheets")]
[assembly: InternalsVisibleTo("UnityEngine.UIElements.Tests.Utils")]
[assembly: InternalsVisibleTo("UnityEngine.UIElements.Tests.UXML")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.NestedPrefabsBackwardsCompatibility.Tests")]
[assembly: InternalsVisibleTo("Unity.Modules.Subsystems.Tests")]

[assembly: InternalsVisibleTo("Unity.UIElements.TestComponents")]/*UCBP-REMOVE*/
[assembly: InternalsVisibleTo("Unity.UIElements.EditorTests")]
[assembly: InternalsVisibleTo("Unity.UIElements.RuntimeTests")]
[assembly: InternalsVisibleTo("UnityEngine.UI")]

[assembly: InternalsVisibleTo("UnityEditor.GraphToolkitModule")] // com.unity.graphtoolsauthoringframework

// Needed for Baselib CSharp binding access.
[assembly: InternalsVisibleTo("Unity.Networking.Transport")]
[assembly: InternalsVisibleTo("Unity.ucg.QoS")] // TODO(andrews): Remove this when we fix transport
[assembly: InternalsVisibleTo("Unity.Services.QoS")] // TODO: Remove this when we fix transport
[assembly: InternalsVisibleTo("Unity.Logging")]
[assembly: InternalsVisibleTo("Unity.Entities")]
[assembly: InternalsVisibleTo("Unity.Entities.Tests")]
[assembly: InternalsVisibleTo("Unity.Collections")]
[assembly: InternalsVisibleTo("Unity.Runtime")]
[assembly: InternalsVisibleTo("Unity.Core")]
[assembly: InternalsVisibleTo("UnityEngine.Core.Runtime.Tests")]

[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.001")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.002")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.003")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.004")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.005")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.006")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.007")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.008")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.009")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.010")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.011")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.012")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.013")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.014")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.015")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.016")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.017")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.018")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.019")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.020")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.021")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.022")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.023")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridge.024")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridgeDev.001")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridgeDev.002")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridgeDev.003")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridgeDev.004")]
[assembly: InternalsVisibleTo("Unity.InternalAPIEngineBridgeDev.005")]

[assembly: InternalsVisibleTo("Unity.Subsystem.Registration")]
// Note: Don't add InternalsVisibleTo for UnityEngine.UI, because it's editable by users and it shouldn't access internal UnityEngine methods


// Test Assemblies
[assembly: InternalsVisibleTo("Unity.Core.Scripting.AssemblyVersion.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.MemorySettings.Tests.Playmode")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.PlayerConnection.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.Pool.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.Pool.Tests.Playmode")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.Rendering.Meshes.Tests.Runtime")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.UnsafeUtility.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.ProfilerEditor.MemorySnapshot.Tests.Playmode")]
[assembly: InternalsVisibleTo("Unity.CrossModule.ScriptableRenderPipeline.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.CrossModule.ScriptableRenderPipeline.Tests.Runtime")]
[assembly: InternalsVisibleTo("Unity.Modules.PlayableGraph.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.PlayableGraph.Tests")]
[assembly: InternalsVisibleTo("Unity.Modules.GI.RealTimeGI.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.GI.RealTimeGI.Tests.Runtime")]
[assembly: InternalsVisibleTo("Unity.Modules.GI.LightingDataAsset.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Transform.Tests.Runtime")]
[assembly: InternalsVisibleTo("Unity.Transform.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.GI.LightProbes.Tests.Runtime")]
[assembly: InternalsVisibleTo("Unity.GI.ReflectionProbes.Test")]
[assembly: InternalsVisibleTo("Unity.Transform.Tests.Internals")]
[assembly: InternalsVisibleTo("Unity.Hierarchy.PerformanceTests")]
[assembly: InternalsVisibleTo("Unity.Modules.AssetBundle.AssetBundles.Tests.Runtime")]
[assembly: InternalsVisibleTo("BuildPipelineTestUtilities")]
[assembly: InternalsVisibleTo("BuildPipelineTestUtilities-UnityEngine")]
[assembly: InternalsVisibleTo("ContentDirectoryUtilities")]
[assembly: InternalsVisibleTo("ContentBuildTests")]
[assembly: InternalsVisibleTo("Unity.Modules.Core.EditorUtils.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Modules.Umpe.Tests.Editor")]

[assembly: InternalsVisibleTo("Unity.Modules.SceneTemplateEditor.Tests.Editor")]
[assembly: InternalsVisibleTo("com.unity.quicksearch.tests.runtime")] // /*UCBP-REMOVE*/ LoadableReference for SearchColumnTestComponent
// Tests/SRPTests/Projects/MultipleSRP_Tests - needed for DiagnosticSwitch class
[assembly: InternalsVisibleTo("Unity.RenderPipelines.Multiple_SRP.EditorTests")]

// Workspace/Serialization/UnityDataModel/WorkspaceProject
[assembly: InternalsVisibleTo("UDMInternalWorkspaceProject")]

// DataModel Tests assemblies
[assembly: InternalsVisibleTo("TestCodeAssembly")]
[assembly: InternalsVisibleTo("TestBehaviours")]

