// Unity C# reference source
// Copyright (c) Unity Technologies. For terms of use, see
// https://unity3d.com/legal/licenses/Unity_Reference_Only_License

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine.Bindings;
using UnityEngine.Pool;
using UnityEngine.Scripting;
using UnityEngine.UIElements.Layout; // FixedBuffer4<T>
using UnityEngine.UIElements.StyleSheets;
using UnityEngine.UIElements.Unmanaged;


namespace UnityEngine.UIElements
{
    internal sealed partial class UIAnimationBinder
    {
        internal List<KeyValuePair<string, VisualElement>> m_Elements;
        internal Dictionary<PropertyName, VisualElement> m_ElementsMap;

        // Per-(element, id) buffer used during a single IterateOnBoundValues pass to coalesce
        // the up-to-18-channel filter writes per slot into a single ApplyPropertyAnimation call.
        // Lists are pooled and the dictionary is reused across passes (cleared on flush).
        private Dictionary<(VisualElement element, StylePropertyId id), List<FilterFunction>> m_PendingFilterWrites;
        private bool m_BatchingFilterWrites;

        [VisibleToOtherModules("UnityEditor.UIToolkitAuthoringModule")]
        internal static int GetChannelCount(StylePropertyId id)
        {
            return m_ChannelCount[(int)id];
        }

        [VisibleToOtherModules("UnityEditor.UIToolkitAuthoringModule")]
        internal static PropertyType GetPropertyTypeMapping(StylePropertyId id)
        {
            return m_PropertyTypeMapping[(int)id];
        }

        [VisibleToOtherModules("UnityEditor.UIToolkitAuthoringModule")]
        internal void IncrementBoundElementsStyleVersion()
        {
            if (m_Elements == null)
                return;

            // Surviving curves flip up-to-date back to 1 on the next sample.
            InvalidateBoundValueCaches();

            for (int i = 0; i < m_Elements.Count; i++)
            {
                var element = m_Elements[i].Value;
                if (element == null)
                    continue;

                element.computedStyle.InvalidateMatchingRulesCache();
                element.IncrementVersion(VersionChangeType.StyleSheet | VersionChangeType.Styles);
            }
        }

        [VisibleToOtherModules("UnityEditor.UIToolkitAuthoringModule")]
        internal static AnimationChannelKind GetChannelKind(StylePropertyId id, int channel)
        {
            return m_ChannelKinds[(int)m_PropertyTypeMapping[(int)id]][channel];
        }

        // Per-channel suffixes / kinds are generated by UIElementsGenerator. Tables are indexed
        // by PropertyType (not StylePropertyId) so every id with the same kind shares a row.
        [VisibleToOtherModules("UnityEditor.UIToolkitAuthoringModule")]
        internal static IReadOnlyList<string> GetChannelSuffixes(StylePropertyId id)
        {
            return m_ChannelSuffixes[(int)m_PropertyTypeMapping[(int)id]];
        }

        [VisibleToOtherModules("UnityEditor.UIToolkitAuthoringModule")]
        internal static int StylePropertyIdCount
        {
            [VisibleToOtherModules("UnityEditor.UIToolkitAuthoringModule")]
            get => m_ChannelCount.Length;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        int GetElementCount() => m_Elements?.Count ?? -1;

        [VisibleToOtherModules("UnityEditor.UIToolkitAuthoringModule")]
        internal void SetFloatValue(int elementIndex, int propertyId, int channel, float value)
        {
            if (elementIndex < 0 || elementIndex >= GetElementCount())
                return;

            var e = m_Elements[elementIndex].Value;
            StylePropertyId id = (StylePropertyId)propertyId;

            Debug.Assert(channel < GetChannelCount(id));

            switch (GetPropertyTypeMapping(id))
            {
                case PropertyType.Float:
                    e.computedStyle.ApplyPropertyAnimation(e, id, value);
                    break;

                case PropertyType.Rotate:
                    var r = e.computedStyle.ReadPropertyAnimationRotate(id);
                    r.angle = Angle.Degrees(value);
                    e.computedStyle.ApplyPropertyAnimation(e, id, r);
                    break;

                case PropertyType.Translate:
                {
                    // Layout: 0/1 = x LengthBlock, 2/3 = y LengthBlock, 4 = z (float).
                    Translate t = e.computedStyle.ReadPropertyAnimationTranslate(id);
                    var x = t.x;
                    var y = t.y;
                    var z = t.z;
                    if (channel <= 1)
                        x = AnimationLengthChannel.Write(x, channel, value);
                    else if (channel <= 3)
                        y = AnimationLengthChannel.Write(y, channel - 2, value);
                    else
                        z = value;
                    t = new Translate(x, y, z);
                    e.computedStyle.ApplyPropertyAnimation(e, id, t);
                }
                break;

                case PropertyType.Scale:
                {
                    var s = e.computedStyle.ReadPropertyAnimationScale(id).value;
                    if (channel == 0)
                        s.x = value;
                    else if (channel == 1)
                        s.y = value;
                    else if (channel == 2)
                        s.z = value;
                    e.computedStyle.ApplyPropertyAnimation(e, id, new Scale(s));
                }
                break;

                case PropertyType.Color:
                    var c = e.computedStyle.ReadPropertyAnimationColor(id);
                    if (channel == 0)
                        c.r = value;
                    else if (channel == 1)
                        c.g = value;
                    else if (channel == 2)
                        c.b = value;
                    else if (channel == 3)
                        c.a = value;
                    e.computedStyle.ApplyPropertyAnimation(e, id, c);
                    break;

                case PropertyType.Ratio:
                    e.computedStyle.ApplyPropertyAnimation(e, id, new Ratio(value));
                    break;

                case PropertyType.Int or PropertyType.Enum:
                    e.computedStyle.ApplyPropertyAnimation(e, id, BitConverter.SingleToInt32Bits(value));
                    break;

                case PropertyType.Length:
                {
                    // Channels match AnimationLengthChannel layout (0 = value, 1 = unit).
                    var l = e.computedStyle.ReadPropertyAnimationLength(id);
                    l = AnimationLengthChannel.Write(l, channel, value);
                    e.computedStyle.ApplyPropertyAnimation(e, id, l);
                    break;
                }

                case PropertyType.BackgroundPosition:
                {
                    // Layout: 0 = keyword (discrete int), 1/2 = offset LengthBlock.
                    var bp = e.computedStyle.ReadPropertyAnimationBackgroundPosition(id);
                    if (channel == 0)
                        bp.keyword = (BackgroundPositionKeyword)BitConverter.SingleToInt32Bits(value);
                    else
                        bp.offset = AnimationLengthChannel.Write(bp.offset, channel - 1, value);
                    e.computedStyle.ApplyPropertyAnimation(e, id, bp);
                    break;
                }

                case PropertyType.BackgroundRepeat:
                {
                    // Layout: 0 = x (Repeat enum), 1 = y (Repeat enum).
                    var br = e.computedStyle.ReadPropertyAnimationBackgroundRepeat(id);
                    if (channel == 0)
                        br.x = (Repeat)BitConverter.SingleToInt32Bits(value);
                    else if (channel == 1)
                        br.y = (Repeat)BitConverter.SingleToInt32Bits(value);
                    e.computedStyle.ApplyPropertyAnimation(e, id, br);
                    break;
                }

                case PropertyType.BackgroundSize:
                {
                    // Layout: 0 = sizeType, 1/2 = x LengthBlock, 3/4 = y LengthBlock.
                    // Reassemble via the 3-arg ctor since the public setters mutate siblings.
                    var bs = e.computedStyle.ReadPropertyAnimationBackgroundSize(id);
                    var sizeType = bs.sizeType;
                    var x = bs.x;
                    var y = bs.y;
                    if (channel == 0)
                        sizeType = (BackgroundSizeType)BitConverter.SingleToInt32Bits(value);
                    else if (channel <= 2)
                        x = AnimationLengthChannel.Write(x, channel - 1, value);
                    else
                        y = AnimationLengthChannel.Write(y, channel - 3, value);
                    e.computedStyle.ApplyPropertyAnimation(e, id, new BackgroundSize(sizeType, x, y));
                    break;
                }

                case PropertyType.TextShadow:
                {
                    // Layout: 0..3 = color.r/g/b/a, 4..5 = offset.x/y, 6 = blurRadius.
                    var ts = e.computedStyle.ReadPropertyAnimationTextShadow(id);
                    switch (channel)
                    {
                        case 0: ts.color.r = value; break;
                        case 1: ts.color.g = value; break;
                        case 2: ts.color.b = value; break;
                        case 3: ts.color.a = value; break;
                        case 4: ts.offset.x = value; break;
                        case 5: ts.offset.y = value; break;
                        case 6: ts.blurRadius = value; break;
                    }
                    e.computedStyle.ApplyPropertyAnimation(e, id, ts);
                    break;
                }

                case PropertyType.TransformOrigin:
                {
                    // Layout: 0/1 = x LengthBlock, 2/3 = y LengthBlock. z exists on the struct but is not animated.
                    var to = e.computedStyle.ReadPropertyAnimationTransformOrigin(id);
                    var x = to.x;
                    var y = to.y;
                    if (channel <= 1)
                        x = AnimationLengthChannel.Write(x, channel, value);
                    else
                        y = AnimationLengthChannel.Write(y, channel - 2, value);
                    e.computedStyle.ApplyPropertyAnimation(e, id, new TransformOrigin(x, y, to.z));
                    break;
                }

                case PropertyType.Filter:
                {
                    // PPtr `.customDefinition` sub-channels are routed to SetObjectValue; we only see Float / Int here.
                    int filterIndex = channel / kFilterChannelsPerSlot;
                    int subChannel = channel % kFilterChannelsPerSlot;
                    var filterList = GetOrLoadFilterList(e, id);
                    if (subChannel == kFilterTypeSubChannel)
                        WriteFilterType(filterList, filterIndex, BitConverter.SingleToInt32Bits(value));
                    else if (subChannel >= kFilterParamSubChannelStart)
                        WriteFilterValue(filterList, filterIndex, subChannel - kFilterParamSubChannelStart, value);
                    if (!m_BatchingFilterWrites)
                        FlushPendingFilterWrites();
                    break;
                }

            }

        }
      
        internal float GetFloatValue(int elementIndex, int propertyId, int channel)
        {
            if (elementIndex < 0 || elementIndex >= GetElementCount())
                return 0;

            var element = m_Elements[elementIndex].Value;
            StylePropertyId id = (StylePropertyId)propertyId;

            Debug.Assert(channel < GetChannelCount(id));

            return GetPropertyTypeMapping(id) switch
            {
                PropertyType.Length => AnimationLengthChannel.ReadFloat(
                    element.computedStyle.ReadPropertyAnimationLength(id), channel),
                PropertyType.Float => element.computedStyle.ReadPropertyAnimationFloat(id),
                PropertyType.Int => BitConverter.Int32BitsToSingle(element.computedStyle.ReadPropertyAnimationInt(id)),
                PropertyType.Enum => BitConverter.Int32BitsToSingle(element.computedStyle.ReadPropertyAnimationInt(id)),
                PropertyType.Color => element.computedStyle.ReadPropertyAnimationColor(id)[channel],
                PropertyType.Translate => channel <= 1
                    ? AnimationLengthChannel.ReadFloat(element.computedStyle.ReadPropertyAnimationTranslate(id).x, channel)
                    : channel <= 3
                        ? AnimationLengthChannel.ReadFloat(element.computedStyle.ReadPropertyAnimationTranslate(id).y, channel - 2)
                        : element.computedStyle.ReadPropertyAnimationTranslate(id).z,
                PropertyType.Rotate => element.computedStyle.ReadPropertyAnimationRotate(id).angle.ToDegrees(),
                PropertyType.Scale => element.computedStyle.ReadPropertyAnimationScale(id).value[channel],
                PropertyType.Ratio => element.computedStyle.ReadPropertyAnimationRatio(id),
                PropertyType.BackgroundPosition => channel == 0
                    ? BitConverter.Int32BitsToSingle((int)element.computedStyle.ReadPropertyAnimationBackgroundPosition(id).keyword)
                    : AnimationLengthChannel.ReadFloat(element.computedStyle.ReadPropertyAnimationBackgroundPosition(id).offset, channel - 1),
                PropertyType.BackgroundRepeat => channel switch
                {
                    0 => BitConverter.Int32BitsToSingle((int)element.computedStyle.ReadPropertyAnimationBackgroundRepeat(id).x),
                    1 => BitConverter.Int32BitsToSingle((int)element.computedStyle.ReadPropertyAnimationBackgroundRepeat(id).y),
                    _ => throw new NotImplementedException(),
                },
                PropertyType.BackgroundSize => channel == 0
                    ? BitConverter.Int32BitsToSingle((int)element.computedStyle.ReadPropertyAnimationBackgroundSize(id).sizeType)
                    : channel <= 2
                        ? AnimationLengthChannel.ReadFloat(element.computedStyle.ReadPropertyAnimationBackgroundSize(id).x, channel - 1)
                        : AnimationLengthChannel.ReadFloat(element.computedStyle.ReadPropertyAnimationBackgroundSize(id).y, channel - 3),
                PropertyType.TextShadow => channel switch
                {
                    // Layout: 0..3 = color.r/g/b/a, 4..5 = offset.x/y, 6 = blurRadius.
                    0 => element.computedStyle.ReadPropertyAnimationTextShadow(id).color.r,
                    1 => element.computedStyle.ReadPropertyAnimationTextShadow(id).color.g,
                    2 => element.computedStyle.ReadPropertyAnimationTextShadow(id).color.b,
                    3 => element.computedStyle.ReadPropertyAnimationTextShadow(id).color.a,
                    4 => element.computedStyle.ReadPropertyAnimationTextShadow(id).offset.x,
                    5 => element.computedStyle.ReadPropertyAnimationTextShadow(id).offset.y,
                    6 => element.computedStyle.ReadPropertyAnimationTextShadow(id).blurRadius,
                    _ => throw new NotImplementedException(),
                },

                PropertyType.TransformOrigin => channel <= 1
                    ? AnimationLengthChannel.ReadFloat(element.computedStyle.ReadPropertyAnimationTransformOrigin(id).x, channel)
                    : AnimationLengthChannel.ReadFloat(element.computedStyle.ReadPropertyAnimationTransformOrigin(id).y, channel - 2),

                // PPtr `.customDefinition` sub-channels go through GetObjectValue.
                PropertyType.Filter => ReadFilterFloatOrTypeChannel(element, channel),

                // PPtr-kind properties are routed through GetObjectValue; the rest advertise zero
                // animatable channels in the generator tables, so the binder never reaches here.
                PropertyType.Shorthand => throw new NotImplementedException(),
                PropertyType.Background => throw new NotImplementedException(),
                PropertyType.Font => throw new NotImplementedException(),
                PropertyType.FontDefinition => throw new NotImplementedException(),
                PropertyType.Cursor => throw new NotImplementedException(),
                PropertyType.TextAutoSize => throw new NotImplementedException(),
                PropertyType.List => throw new NotImplementedException(),
                PropertyType.MaterialDefinition => throw new NotImplementedException(),
                _ => throw new NotImplementedException(),// Why does c# think the list is not exaustive? seems related to the cast...
            };


        }

        [VisibleToOtherModules("UnityEditor.UIToolkitAuthoringModule")]
        internal void SetObjectValue(int elementIndex, int propertyId, int channel, EntityId value)
        {
            if (elementIndex < 0 || elementIndex >= GetElementCount())
                return;

            var e = m_Elements[elementIndex].Value;
            StylePropertyId id = (StylePropertyId)propertyId;

            Debug.Assert(channel < GetChannelCount(id));

            switch (GetPropertyTypeMapping(id))
            {
                case PropertyType.Background:
                case PropertyType.Font:
                case PropertyType.FontDefinition:
                    e.computedStyle.ApplyPropertyAnimation(e, id, value);
                    break;

                case PropertyType.MaterialDefinition:
                {
                    // The EntityId overload stores into UnmanagedMaterialDefinition, which needs
                    // a managed Material to repopulate property values; go through the typed overload.
                    var mat = (Material)Resources.EntityIdToObject(value);
                    e.computedStyle.ApplyPropertyAnimation(e, id, new MaterialDefinition(mat));
                    break;
                }

                case PropertyType.Filter:
                {
                    // Only `.customDefinition` is a PPtr; `.p<n>` and `.type` arrive through SetFloatValue.
                    int filterIndex = channel / kFilterChannelsPerSlot;
                    int subChannel = channel % kFilterChannelsPerSlot;
                    if (subChannel == kFilterCustomDefinitionSubChannel)
                    {
                        var newDef = value != EntityId.None
                            ? Resources.EntityIdToObject(value) as FilterFunctionDefinition
                            : null;
                        var filterList = GetOrLoadFilterList(e, id);
                        WriteFilterCustomDefinition(filterList, filterIndex, newDef);
                        if (!m_BatchingFilterWrites)
                            FlushPendingFilterWrites();
                    }
                    break;
                }
            }
        }

        internal EntityId GetObjectValue(int elementIndex, int propertyId, int channel)
        {
            if (elementIndex < 0 || elementIndex >= GetElementCount())
                return EntityId.None;

            var element = m_Elements[elementIndex].Value;
            StylePropertyId id = (StylePropertyId)propertyId;

            Debug.Assert(channel < GetChannelCount(id));

            return GetPropertyTypeMapping(id) switch
            {
                PropertyType.Background => element.computedStyle.ReadPropertyAnimationEntityId(id),
                PropertyType.Font => element.computedStyle.ReadPropertyAnimationEntityId(id),
                PropertyType.FontDefinition => element.computedStyle.ReadPropertyAnimationEntityId(id),
                PropertyType.MaterialDefinition => id switch
                {
                    StylePropertyId.UnityMaterial => element.computedStyle.unityMaterial.material,
                    _ => throw new NotImplementedException(),
                },

                //invalid type
                PropertyType.Length => throw new InvalidOperationException(),
                PropertyType.Float => throw new InvalidOperationException(),
                PropertyType.Int => throw new InvalidOperationException(),
                PropertyType.Enum => throw new InvalidOperationException(),
                PropertyType.Color => throw new InvalidOperationException(),
                PropertyType.Translate => throw new InvalidOperationException(),
                PropertyType.Rotate => throw new InvalidOperationException(),
                PropertyType.Scale => throw new InvalidOperationException(),
                PropertyType.Ratio => throw new InvalidOperationException(),
                PropertyType.TransformOrigin => throw new InvalidOperationException(),
                PropertyType.Shorthand => throw new InvalidOperationException(),
                PropertyType.BackgroundPosition => throw new InvalidOperationException(),
                PropertyType.BackgroundRepeat => throw new InvalidOperationException(),
                PropertyType.BackgroundSize => throw new InvalidOperationException(),
                PropertyType.TextShadow => throw new InvalidOperationException(),
                PropertyType.TextAutoSize => throw new InvalidOperationException(),

                // `.p<n>` and `.type` go through GetFloatValue; only `.customDefinition` arrives here.
                PropertyType.Filter => ReadFilterCustomDefinitionChannel(element, channel),

                //Not implemented
                PropertyType.Cursor => throw new NotImplementedException(),
                PropertyType.List => throw new NotImplementedException(),
                _ => throw new NotImplementedException(),// Why does c# think the list is not exhaustive? seems related to the cast...
            };
        }

        // Filter layout per slot: `.type` (Int, sub 0), `.customDefinition` (PPtr, sub 1),
        // 16 Float `.p<n>` (sub 2..17). Param sub encodes (paramIndex*4 + component); component
        // is 0 for Float, r/g/b/a for Color. Mirrored in StylePropertyDefinitions.cs.
        [VisibleToOtherModules("UnityEditor.UIToolkitAuthoringModule")]
        internal const int kFilterSlotCount = 4;
        [VisibleToOtherModules("UnityEditor.UIToolkitAuthoringModule")]
        internal const int kFilterParamChannelsPerSlot = 16;
        internal const int kFilterTypeSubChannel = 0;
        internal const int kFilterCustomDefinitionSubChannel = 1;
        internal const int kFilterParamSubChannelStart = 2;
        [VisibleToOtherModules("UnityEditor.UIToolkitAuthoringModule")]
        internal const int kFilterChannelsPerSlot = kFilterParamSubChannelStart + kFilterParamChannelsPerSlot;

        // Splits a flat channel into the (slot, sub-channel) pair and dispatches `.p<n>` / `.type`.
        // The Int `.type` channel rides the float pipeline as a bit-cast int.
        private static float ReadFilterFloatOrTypeChannel(VisualElement element, int channel)
        {
            int filterIndex = channel / kFilterChannelsPerSlot;
            int subChannel = channel % kFilterChannelsPerSlot;
            if (subChannel == kFilterTypeSubChannel)
                return BitConverter.Int32BitsToSingle((int)ReadFilterType(element, filterIndex));
            if (subChannel >= kFilterParamSubChannelStart)
                return ReadFilterValue(element, filterIndex, subChannel - kFilterParamSubChannelStart);

            // PPtr sub-channels are routed to GetObjectValue; arriving here is a misdispatch.
            return 0f;
        }

        private static EntityId ReadFilterCustomDefinitionChannel(VisualElement element, int channel)
        {
            int filterIndex = channel / kFilterChannelsPerSlot;
            int subChannel = channel % kFilterChannelsPerSlot;
            if (subChannel == kFilterCustomDefinitionSubChannel)
                return ReadFilterCustomDefinition(element, filterIndex);
            return EntityId.None;
        }

        // Owns the (paramIndex, component) packing for `.p<n>` so callers stay flat. Returns 0 for
        // out-of-range slot / param / component so unauthored elements don't fault.
        private static float ReadFilterValue(VisualElement element, int filterIndex, int subChannel)
        {
            var filterList = element.computedStyle.rareData.Read().filter;
            if (filterIndex < 0 || filterIndex >= filterList.Count)
                return 0f;

            int paramIndex = subChannel >> 2;
            int component = subChannel & 0x3;

            FilterFunction f = filterList[filterIndex];
            if (paramIndex < 0 || paramIndex >= f.parameterCount)
                return 0f;

            FilterParameter p = f.GetParameter(paramIndex);
            if (p.type == FilterParameterType.Float)
                return p.floatValue;

            return component switch
            {
                0 => p.colorValue.r,
                1 => p.colorValue.g,
                2 => p.colorValue.b,
                3 => p.colorValue.a,
                _ => 0f,
            };
        }

        private static FilterFunctionType ReadFilterType(VisualElement element, int filterIndex)
        {
            var filterList = element.computedStyle.rareData.Read().filter;
            if (filterIndex < 0 || filterIndex >= filterList.Count)
                return FilterFunctionType.None;

            FilterFunction f = filterList[filterIndex];
            return f.type;
        }

        private static EntityId ReadFilterCustomDefinition(VisualElement element, int filterIndex)
        {
            var filterList = element.computedStyle.rareData.Read().filter;
            if (filterIndex < 0 || filterIndex >= filterList.Count)
                return EntityId.None;

            FilterFunction f = filterList[filterIndex];
            FilterFunctionDefinition def = f.customDefinition;
            return def != null ? def.GetEntityId() : EntityId.None;
        }

        // Snapshot helper for the recording bridge, which can't reach RareData / the unmanaged list directly.
        [VisibleToOtherModules("UnityEditor.UIToolkitAuthoringModule")]
        internal static List<FilterFunction> ReadFilterListSnapshot(VisualElement element)
        {
            List<FilterFunction> snapshot = null;
            if (element != null)
                element.computedStyle.rareData.Read().filter.CopyTo(ref snapshot);
            return snapshot ?? new List<FilterFunction>();
        }

        // Owns the (paramIndex, component) packing so callers stay flat. Lazily materialises slot
        // and parameter on the cached filterList; the flush pass calls ApplyPropertyAnimation.
        private static void WriteFilterValue(List<FilterFunction> filterList, int filterIndex, int subChannel, float value)
        {
            if (filterIndex < 0 || filterIndex >= kFilterSlotCount
                || subChannel < 0 || subChannel >= kFilterParamChannelsPerSlot)
                return;

            int paramIndex = subChannel >> 2;
            int component = subChannel & 0x3;

            while (filterList.Count <= filterIndex)
                filterList.Add(new FilterFunction());

            FilterFunction f = filterList[filterIndex];

            // Newly-added params default to Float for component 0, Color otherwise (suffix .r/.g/.b/.a).
            while (f.parameterCount <= paramIndex)
            {
                FilterParameter newParam = component != 0
                    ? new FilterParameter(Color.clear)
                    : new FilterParameter(0f);
                f.AddParameter(newParam);
            }

            FilterParameter p = f.GetParameter(paramIndex);
            if (p.type == FilterParameterType.Float)
            {
                if (component == 0)
                    p.floatValue = value;
            }
            else
            {
                Color c = p.colorValue;
                switch (component)
                {
                    case 0: c.r = value; break;
                    case 1: c.g = value; break;
                    case 2: c.b = value; break;
                    case 3: c.a = value; break;
                }
                p.colorValue = c;
            }
            f.SetParameter(paramIndex, p);
            filterList[filterIndex] = f;
        }

        // Only re-seeds parameters on actual type transitions so concurrent `.p<n>` curves
        // don't get stomped every frame.
        private static void WriteFilterType(List<FilterFunction> filterList, int filterIndex, int rawType)
        {
            if (filterIndex < 0 || filterIndex >= kFilterSlotCount)
                return;

            // Discrete int curves store raw bit patterns; clamp out-of-range samples to None.
            FilterFunctionType newType = FilterFunctionType.None;
            if (Enum.IsDefined(typeof(FilterFunctionType), rawType))
                newType = (FilterFunctionType)rawType;

            // A freshly-padded slot may already match newType; still apply so the slot persists.
            int originalCount = filterList.Count;
            while (filterList.Count <= filterIndex)
                filterList.Add(new FilterFunction());
            bool listGrew = filterList.Count != originalCount;

            FilterFunction f = filterList[filterIndex];
            if (!listGrew && f.type == newType)
                return;

            if (f.type != newType)
            {
                f.type = newType;
                if (newType != FilterFunctionType.Custom)
                    f.customDefinition = null;

                ReseedParametersFromDefinition(ref f, f.GetDefinition(), useInterpolationDefault: false);
            }

            filterList[filterIndex] = f;
        }

        // Re-seeds parameters when a slot's type/definition changes, preserving any
        // type-compatible value a sibling `.p<n>` curve already wrote in the same
        // IterateOnBoundValues pass (otherwise a trailing type write clobbers them
        // every frame). Builtins use defaultValue; custom defs use interpolationDefault.
        private static void ReseedParametersFromDefinition(ref FilterFunction f, FilterFunctionDefinition def, bool useInterpolationDefault)
        {
            int targetCount = def?.parameters?.Length ?? 0;
            int existingCount = f.parameterCount;

            Span<FilterParameter> existing = stackalloc FilterParameter[FixedBuffer4<FilterParameter>.Length];
            for (int i = 0; i < existingCount; ++i)
                existing[i] = f.GetParameter(i);

            f.ClearParameters();
            for (int i = 0; i < targetCount; ++i)
            {
                FilterParameter fallback = useInterpolationDefault
                    ? def.parameters[i].interpolationDefaultValue
                    : def.parameters[i].defaultValue;
                // Preserve only type-compatible values; incompatible kinds fall back to default.
                FilterParameter value = (i < existingCount && existing[i].type == fallback.type)
                    ? existing[i]
                    : fallback;
                f.AddParameter(value);
            }
        }

        // `.customDefinition` PPtr curve handler. The recording bridge emits this curve
        // unconditionally for every animated slot, so we receive `newDef == null` for
        // builtin types - treat that as a no-op rather than forcing `type = Custom`.
        private static void WriteFilterCustomDefinition(List<FilterFunction> filterList, int filterIndex, FilterFunctionDefinition newDef)
        {
            if (filterIndex < 0 || filterIndex >= kFilterSlotCount)
                return;

            // Null def for a non-existent slot: nothing to do (the `.type` curve owns slot creation).
            if (newDef == null && filterIndex >= filterList.Count)
                return;

            while (filterList.Count <= filterIndex)
                filterList.Add(new FilterFunction());

            FilterFunction f = filterList[filterIndex];

            // Null def for a builtin slot: leave it alone.
            if (newDef == null && f.type != FilterFunctionType.Custom)
                return;

            if (f.type == FilterFunctionType.Custom && f.customDefinition == newDef)
                return;

            f.type = FilterFunctionType.Custom;
            f.customDefinition = newDef;
            ReseedParametersFromDefinition(ref f, newDef, useInterpolationDefault: true);

            filterList[filterIndex] = f;
        }

        // Returns the pending filter list for (e, id), lazily seeding it from computedStyle on
        // first access. Lists are pooled and released by FlushPendingFilterWrites.
        private List<FilterFunction> GetOrLoadFilterList(VisualElement e, StylePropertyId id)
        {
            m_PendingFilterWrites ??= new Dictionary<(VisualElement, StylePropertyId), List<FilterFunction>>();
            if (!m_PendingFilterWrites.TryGetValue((e, id), out var list))
            {
                list = ListPool<FilterFunction>.Get();
                e.computedStyle.rareData.Read().filter.CopyTo(ref list);
                m_PendingFilterWrites[(e, id)] = list;
            }
            return list;
        }

        // Called after IterateOnBoundValues finishes (and after each non-batched Set*Value
        // call) to push the accumulated filter lists onto each element's computedStyle in
        // a single ApplyPropertyAnimation per (element, id) pair.
        internal void FlushPendingFilterWrites()
        {
            if (m_PendingFilterWrites == null || m_PendingFilterWrites.Count == 0)
                return;

            foreach (var kvp in m_PendingFilterWrites)
            {
                var (e, id) = kvp.Key;
                var list = kvp.Value;
                e.computedStyle.ApplyPropertyAnimation(e, id, list);
                ListPool<FilterFunction>.Release(list);
            }
            m_PendingFilterWrites.Clear();
        }
    }
}
