// Unity C# reference source
// Copyright (c) Unity Technologies. For terms of use, see
// https://unity3d.com/legal/licenses/Unity_Reference_Only_License

using System;
using System.Reflection;
using System.Runtime.InteropServices;
using UnityEngine.Scripting;

namespace UnityEngine
{
    // Copy of the private struct generated by Unity.Compiler package here:
    // https://github.cds.internal.unity3d.com/unity/Unity.Compiler/blob/master/src/Unity.SourceGenerators/MonoScriptInfoGenerator.cs#L199
    // A private type is generated for each assembly, so we can cannot perform a type safe cast or unbox.
    // Using reflection is the only safe way to access the data.
    [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]
    [UsedByNativeCode]
    internal struct MonoScriptData
    {
        // File paths:
        // 4 bytes: Big Endian int, Number of types in file
        // 4 bytes: Big Endian int, FilePath length
        // x bytes: UFT-8 encoded, filePath
        public byte[] FilePathsData;
        //Types are seperated into chunks of types:  [{{isPartial, length, namespace|classname}}, ...]
        // 1 byte:  isPartial, 1 == true
        // 4 bytes: Big Endian int, length of string
        // x bytes: UFT-8 encoded, namespace|classname
        public byte[] TypesData;
        // Total amount of types in 'TypesData'
        public int TotalTypes;
        // Total amount of file paths in 'FilePathsData'
        public int TotalFiles;
        public bool IsEditorOnly;
    }

    internal class ScriptInfoScraper
    {
        [RequiredByNativeCode]
        internal static void GetScrapedData(
            Type t,
            out object filePathsData,
            out object typesData,
            out int totalTypes,
            out int totalFiles,
            out bool isEditorOnly)
        {
            var data = GetScrapedDataInternal(t);
            filePathsData = data.FilePathsData;
            typesData = data.TypesData;
            totalTypes = data.TotalTypes;
            totalFiles = data.TotalFiles;
            isEditorOnly = data.IsEditorOnly;
        }

        private static MonoScriptData GetScrapedDataInternal(Type t)
        {
            if (t == null)
            {
                return new MonoScriptData
                {
                    FilePathsData = Array.Empty<byte>(),
                    TypesData = Array.Empty<byte>(),
                    TotalTypes = 0,
                    TotalFiles = 0,
                    IsEditorOnly = false
                };
            }

            var getMethod = t.GetMethod("Get", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);
            if (getMethod == null)
            {
                return new MonoScriptData
                {
                    FilePathsData = Array.Empty<byte>(),
                    TypesData = Array.Empty<byte>(),
                    TotalTypes = 0,
                    TotalFiles = 0,
                    IsEditorOnly = false
                };
            }

            try
            {
                var scrapedDataObject = getMethod.Invoke(null, null);
                if (scrapedDataObject == null)
                {
                    return new MonoScriptData
                    {
                        FilePathsData = Array.Empty<byte>(),
                        TypesData = Array.Empty<byte>(),
                        TotalTypes = 0,
                        TotalFiles = 0,
                        IsEditorOnly = false
                    };
                }

                var monoScriptDataType = scrapedDataObject.GetType();

                var filePathsField = monoScriptDataType.GetField(nameof(MonoScriptData.FilePathsData), BindingFlags.Instance | BindingFlags.Public);
                var typesDataField = monoScriptDataType.GetField(nameof(MonoScriptData.TypesData), BindingFlags.Instance | BindingFlags.Public);
                var totalTypesField = monoScriptDataType.GetField(nameof(MonoScriptData.TotalTypes), BindingFlags.Instance | BindingFlags.Public);
                var totalFilesField = monoScriptDataType.GetField(nameof(MonoScriptData.TotalFiles), BindingFlags.Instance | BindingFlags.Public);
                var isEditorOnlyField = monoScriptDataType.GetField(nameof(MonoScriptData.IsEditorOnly), BindingFlags.Instance | BindingFlags.Public);

                if (filePathsField == null || typesDataField == null || totalTypesField == null ||
                    totalFilesField == null || isEditorOnlyField == null)
                {
                    return new MonoScriptData
                    {
                        FilePathsData = Array.Empty<byte>(),
                        TypesData = Array.Empty<byte>(),
                        TotalTypes = 0,
                        TotalFiles = 0,
                        IsEditorOnly = false
                    };
                }

                return new MonoScriptData
                {
                    FilePathsData = (byte[])filePathsField.GetValue(scrapedDataObject),
                    TypesData = (byte[])typesDataField.GetValue(scrapedDataObject),
                    TotalTypes = (int)totalTypesField.GetValue(scrapedDataObject),
                    TotalFiles = (int)totalFilesField.GetValue(scrapedDataObject),
                    IsEditorOnly = (bool)isEditorOnlyField.GetValue(scrapedDataObject)
                };
            }
            catch (Exception)
            {
                return new MonoScriptData
                {
                    FilePathsData = Array.Empty<byte>(),
                    TypesData = Array.Empty<byte>(),
                    TotalTypes = 0,
                    TotalFiles = 0,
                    IsEditorOnly = false
                };
            }
        }
    }
}
